models/__init__.py, models/applications.py, models/base_model.py, models/createfile, models/job_history.py, models/jobs.py, models/jobseeker.py, models/recruiters.py
Added Data Classes in the models folder
=> initial add of the class models

tests/test_models/__init__.py, tests/test_models/test_base_model.py, tests/test_models/test_engine/__init__.py
=> Added the tests for BaseModel class

.gitignore, console.py, models/base_model.py, models/engine/db_storage.py, models/jobs.py, mysql/setup_mysql_test.sql, tests/test_models/test_engine/test_db_storage.py
added test database
corrected code in test_db_storage.py file
added console module
=> made further corrections on test_db_storage module

models/base_model.py, models/engine/db_storage.py, mysql/setup_mysql.sql, mysql/setup_mysql_test.sql, tests/test_models/test_engine/test_db_storage.py
Changed the database connection parameters to use environment variables instead of hard code
Completed test parameters for the db_storage
updated the database setup file for development and tests
=> updated the test_db_storage file

.gitignore, api/auth.py, api/tokens.py, console.py, models/base_model.py, models/engine/db_storage.py, models/jobseeker.py, models/recruiters.py
Extended the BaseModel class to take care of API basic authentication and token verifification
Extended the DBStorage module to get search parameters with respect to username and tokens for authentication
Updated the console.py file to the new changes
Updated the auth.py and tokens.py files to the new search parameters and functions
=> udated API token aunthentication for the Jobseeker and Recruiter class

models/engine/db_storage.py, web_static/app.py, web_static/forms.py
Implemented the routes "logout, jobseeker_signup and recruiter_signup"
Extended the DBStorage class to allow for searching by a particular attribute value"
=> added the logoout and signup routes for a recruiter and job seeker

models/engine/db_storage.py, web_static/app.py, web_static/forms.py
Moving to a new computer and trying to merge in the new environment
=> Trying to merge

web_static/app.py, web_static/forms.py, web_static/templates/jobseeker_signup.html
Added display of error is html signup form in jobseeker_signup page
corrected the rendering of signup html pages
=> corrected on route htnl page  rendering

web_static/app.py, web_static/forms.py
Corrected the form validators requirements in Jobseeker class
Added the button text in the sign up forms
=> corrected the app page and the form classes

web_static/app.py
Added the correct route point for the logout redirect
implemented the profile_pic route in recruiter form
=> corrected logout route and implemented profile_pic for recruiter

web_static/app.py
To check for return in logout route
=> pushed the logout route changes again

web_static/app.py, web_static/templates/jobseekerProfile.html
Implemented the routes Jobseeker and recruiter profile display
Updated the jobseekerProfile.html
=> updated the recruiter and jobseeker profile display routes

models/job_history.py, web_static/app.py, web_static/templates/jobseekerProfile.html
Updated app.py for profiles picture
=> Eric backend

models/jobs.py, web_static/app.py, web_static/templates/joblists.html, web_static/templates/recruiterDashboard.html
Updated the routes for joblists, and recruiterDashboard
Updated the class model Jobs in models/jobs.py
=> updated the app, jobs and recruiterDashboard files

.gitignore, alembic.ini, alembic/README, alembic/env.py, alembic/script.py.mako, alembic/versions/aa3c1008995c_created_columns_open_position_and_date_.py, alembic/versions/e4a57e4456bd_changed_data_type_in_column_salary_in_.py
Added Alembic database migration feature
Modified the Jobs class model
=> Added the Alembic database migration feature

web_static/app.py
Added some routes in app.py file
=> updated app.py file

web_static/app.py, web_static/templates/job_details.html
Implemented route from job_details to job application page
Implemented display of job details in the website
=> implemented applied jobs and job details display to the website

web_static/app.py, web_static/forms.py, web_static/templates/job_posting_form.html, web_static/templates/recruiterDashboard.html
Created the PostJob class
Implemented the jobPosting route
Updated the hobPosting.html and the recruiterDashboard.html pages
=> implemented the jobPosting route

web_static/templates/about.html, web_static/templates/joblists.html, web_static/templates/logIn.html
Initial attempt to put flash messages in login, about and joblists pages
=> Initial attempt to put flash messages

web_static/handlers/errors.py
Implemented the error handler for 403 error code
=> Implemented the error handler for 403 error code

web_static/templates/posted_jobs.html, web_static/templates/recruiterDashboard.html, web_static/templates/recruiterProfile.html, web_static/templates/userDashboard.html
updated dashboard and profile routes
=> updated the dashboard html routes

web_static/static/scripts/main.js, web_static/templates/job_details.html
Corrected HTML print for the job details
=> Corrected HTML print for the job details

web_static/static/scripts/main.js
Added check if job.role is empty
=> Added check for empty role content

web_static/routes/views.py, web_static/templates/job_details.html, web_static/templates/recruiterDashboard.html, web_static/templates/userDashboard.html
corrected route resolution in the dashboards and job_details html files
=> corrected route resolution in the dashboards and jo_details html files
